name: Python application

on:
  push:
    branches:
      - release-jul24
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        docker login -u "rupeshm" -p "${{ secrets.DOCKERPW }}"
        docker image build -t rupeshm/gitops:hellov1.2 .
        docker push rupeshm/gitops:hellov1.2
